---
- name: Install Prebid Server
  hosts: prebid_server
  roles:
    - { role: prebid_server-setup, prebid_server_conf: "test.yml", tags: "test" }
    - { role: prebid_server-setup, prebid_server_conf: "us_pro.yml", tags: "pro" }